#!/usr/bin/env bash

_BANG_PATH=$(
  BIN_PATH="$0"
  if [ -L "$BIN_PATH" ]; then
    BIN_PATH=$(readlink "$BIN_PATH")
  fi
  (
    cd $(dirname "$BIN_PATH") > /dev/null
    echo -n "$PWD"
  )
)

. "$_BANG_PATH/modules/core.sh"
. "$_BANG_PATH/modules/module.sh"
b.module.require 'opt'
b.module.require 'path'
b.module.require 'str'
b.module.require 'task'

b.set bang.src_path "$_BANG_PATH"
b.set bang.working_dir "$PWD"


task="$1"
shift

[ -n "$task" ] && b.task.run $task "$@"
